(defparameter x00 t)
(defparameter x01 t)
(defparameter x02 t)
(defparameter x03 t)
(defparameter x04 nil)
(defparameter x05 t)
(defparameter x06 nil)
(defparameter x07 t)
(defparameter x08 nil)
(defparameter x09 t)
(defparameter x10 t)
(defparameter x11 t)
(defparameter x12 t)
(defparameter x13 nil)
(defparameter x14 t)
(defparameter x15 t)
(defparameter x16 t)
(defparameter x17 t)
(defparameter x18 t)
(defparameter x19 nil)
(defparameter x20 t)
(defparameter x21 t)
(defparameter x22 nil)
(defparameter x23 t)
(defparameter x24 t)
(defparameter x25 nil)
(defparameter x26 t)
(defparameter x27 t)
(defparameter x28 t)
(defparameter x29 nil)
(defparameter x30 t)
(defparameter x31 t)
(defparameter x32 nil)
(defparameter x33 t)
(defparameter x34 t)
(defparameter x35 nil)
(defparameter x36 nil)
(defparameter x37 t)
(defparameter x38 t)
(defparameter x39 t)
(defparameter x40 nil)
(defparameter x41 nil)
(defparameter x42 nil)
(defparameter x43 nil)
(defparameter x44 t)
(defparameter y00 t)
(defparameter y01 t)
(defparameter y02 t)
(defparameter y03 t)
(defparameter y04 t)
(defparameter y05 nil)
(defparameter y06 nil)
(defparameter y07 nil)
(defparameter y08 nil)
(defparameter y09 nil)
(defparameter y10 t)
(defparameter y11 nil)
(defparameter y12 nil)
(defparameter y13 nil)
(defparameter y14 t)
(defparameter y15 nil)
(defparameter y16 nil)
(defparameter y17 t)
(defparameter y18 nil)
(defparameter y19 t)
(defparameter y20 nil)
(defparameter y21 t)
(defparameter y22 t)
(defparameter y23 nil)
(defparameter y24 nil)
(defparameter y25 nil)
(defparameter y26 t)
(defparameter y27 t)
(defparameter y28 t)
(defparameter y29 nil)
(defparameter y30 nil)
(defparameter y31 nil)
(defparameter y32 t)
(defparameter y33 nil)
(defparameter y34 nil)
(defparameter y35 t)
(defparameter y36 nil)
(defparameter y37 nil)
(defparameter y38 nil)
(defparameter y39 t)
(defparameter y40 t)
(defparameter y41 t)
(defparameter y42 t)
(defparameter y43 t)
(defparameter y44 t)

(defun xor (a b)
  "Perform an exclusive OR operation."
  (and (or a b) (not (and a b))))

(ignore-errors (defparameter cgm (and ktr qkd)))
(ignore-errors (defparameter smb (and y41 x41)))
(ignore-errors (defparameter kmt (and gst gtv)))
(ignore-errors (defparameter bfq (xor y29 x29)))
(ignore-errors (defparameter z07 (xor hqs jmb)))
(ignore-errors (defparameter bdr (and x03 y03)))
(ignore-errors (defparameter z30 (xor gbs rrg)))
(ignore-errors (defparameter dqf (and gbs rrg)))
(ignore-errors (defparameter wpd (and pgs jhf)))
(ignore-errors (defparameter z27 (xor rbr frj)))
(ignore-errors (defparameter jrp (or vsr gng)))
(ignore-errors (defparameter fjs (or knw hwq)))
(ignore-errors (defparameter vbf (and tsp vng)))
(ignore-errors (defparameter z45 (or fpg dqg)))
(ignore-errors (defparameter vjq (or wpd smb)))
(ignore-errors (defparameter z26 (xor fcn pmf)))
(ignore-errors (defparameter hvf (or dqf tmm)))
(ignore-errors (defparameter ghc (and pmq ggj)))
(ignore-errors (defparameter dcg (and dgk ppk)))
(ignore-errors (defparameter z22 (and y22 x22)))
(ignore-errors (defparameter qth (and hqs jmb)))
(ignore-errors (defparameter tgg (and pmf fcn)))
(ignore-errors (defparameter rhg (and y28 x28)))
(ignore-errors (defparameter z05 (xor pvb jbd)))
(ignore-errors (defparameter z13 (xor cqb pbd)))
(ignore-errors (defparameter dgj (or dcg vgw)))
(ignore-errors (defparameter psh (and mpj jrp)))
(ignore-errors (defparameter ggj (xor y39 x39)))
(ignore-errors (defparameter vvm (xor y38 x38)))
(ignore-errors (defparameter dqg (and rrq gjw)))
(ignore-errors (defparameter vkh (and y23 x23)))
(ignore-errors (defparameter pgs (xor x41 y41)))
(ignore-errors (defparameter dwm (or jsb pqq)))
(ignore-errors (defparameter qcj (and x15 y15)))
(ignore-errors (defparameter qrq (and qnq ftn)))
(ignore-errors (defparameter rrg (xor x30 y30)))
(ignore-errors (defparameter rmm (xor y12 x12)))
(ignore-errors (defparameter z10 (xor qnq ftn)))
(ignore-errors (defparameter cmn (or qwd ntb)))
(ignore-errors (defparameter hct (and y01 x01)))
(ignore-errors (defparameter pbq (or ncj dvw)))
(ignore-errors (defparameter dcf (or pdq rhg)))
(ignore-errors (defparameter cmd (and y13 x13)))
(ignore-errors (defparameter bgs (and pvc tdm)))
(ignore-errors (defparameter fcn (or rws gwq)))
(ignore-errors (defparameter fpg (and x44 y44)))
(ignore-errors (defparameter cgv (and wss hgw)))
(ignore-errors (defparameter chb (and y04 x04)))
(ignore-errors (defparameter z40 (xor qbn dhr)))
(ignore-errors (defparameter z42 (xor cpr vjq)))
(ignore-errors (defparameter tpp (and rhk vsn)))
(ignore-errors (defparameter z25 (xor dwm cnn)))
(ignore-errors (defparameter nhj (or jrk nhp)))
(ignore-errors (defparameter pmq (or jnb ctv)))
(ignore-errors (defparameter pqp (and x42 y42)))
(ignore-errors (defparameter knk (and dck qrb)))
(ignore-errors (defparameter z12 (xor vmv rmm)))
(ignore-errors (defparameter vkv (or vbf ksh)))
(ignore-errors (defparameter ncj (and y19 x19)))
(ignore-errors (defparameter frr (or qth ggw)))
(ignore-errors (defparameter z24 (xor qbr qsr)))
(ignore-errors (defparameter dvw (and grf wfs)))
(ignore-errors (defparameter qnq (or csw tbc)))
(ignore-errors (defparameter qdj (and x31 y31)))
(ignore-errors (defparameter qgg (xor y20 x20)))
(ignore-errors (defparameter cvf (and x32 y32)))
(ignore-errors (defparameter pqq (and qbr qsr)))
(ignore-errors (defparameter jnb (and vvm dnk)))
(ignore-errors (defparameter pdq (and bst stp)))
(ignore-errors (defparameter ctv (and y38 x38)))
(ignore-errors (defparameter gbs (xor bfq dcf)))
(ignore-errors (defparameter gsm (and x12 y12)))
(ignore-errors (defparameter qsr (xor y24 x24)))
(ignore-errors (defparameter z08 (and vqp frr)))
(ignore-errors (defparameter pbd (xor y13 x13)))
(ignore-errors (defparameter dgk (or jth dnn)))
(ignore-errors (defparameter jbd (xor y05 x05)))
(ignore-errors (defparameter rhk (and y00 x00)))
(ignore-errors (defparameter z23 (xor fhs fjs)))
(ignore-errors (defparameter z11 (xor gtv gst)))
(ignore-errors (defparameter mfj (and y37 x37)))
(ignore-errors (defparameter gtc (xor y15 x15)))
(ignore-errors (defparameter mqv (and y11 x11)))
(ignore-errors (defparameter qrb (or bkg ktg)))
(ignore-errors (defparameter gtv (xor y11 x11)))
(ignore-errors (defparameter csw (and x09 y09)))
(ignore-errors (defparameter rbt (and dhr qbn)))
(ignore-errors (defparameter z38 (xor vvm dnk)))
(ignore-errors (defparameter vng (or cvf bgq)))
(ignore-errors (defparameter wfs (or hpp sgw)))
(ignore-errors (defparameter z16 (xor djg kpw)))
(ignore-errors (defparameter kpw (xor x16 y16)))
(ignore-errors (defparameter dgr (and x27 y27)))
(ignore-errors (defparameter gwq (and y25 x25)))
(ignore-errors (defparameter sgw (and dgj stq)))
(ignore-errors (defparameter z33 (xor tsp vng)))
(ignore-errors (defparameter cqb (or gsm sft)))
(ignore-errors (defparameter vmv (or kmt mqv)))
(ignore-errors (defparameter z36 (xor qvh fpc)))
(ignore-errors (defparameter fpc (or ptf psh)))
(ignore-errors (defparameter gjw (or wjm cgm)))
(ignore-errors (defparameter qbr (or vkh fdc)))
(ignore-errors (defparameter tsp (xor y33 x33)))
(ignore-errors (defparameter grf (xor x19 y19)))
(ignore-errors (defparameter rrq (xor x44 y44)))
(ignore-errors (defparameter jdj (and pwg mbr)))
(ignore-errors (defparameter mjj (or wrm cgv)))
(ignore-errors (defparameter z35 (xor jrp mpj)))
(ignore-errors (defparameter z31 (xor hvf pfk)))
(ignore-errors (defparameter cpr (xor x42 y42)))
(ignore-errors (defparameter cdf (xor x22 y22)))
(ignore-errors (defparameter tmm (and x30 y30)))
(ignore-errors (defparameter z21 (xor bnv nhj)))
(ignore-errors (defparameter wjm (and y43 x43)))
(ignore-errors (defparameter z04 (xor hfw ggh)))
(ignore-errors (defparameter z09 (xor dnc pjb)))
(ignore-errors (defparameter z17 (xor ppk dgk)))
(ignore-errors (defparameter stp (xor y28 x28)))
(ignore-errors (defparameter z15 (xor mjj gtc)))
(ignore-errors (defparameter hpp (and y18 x18)))
(ignore-errors (defparameter sjw (and x06 y06)))
(ignore-errors (defparameter dnc (or mpr thm)))
(ignore-errors (defparameter z02 (xor mbr pwg)))
(ignore-errors (defparameter frc (and y26 x26)))
(ignore-errors (defparameter thm (xor frr vqp)))
(ignore-errors (defparameter pwg (xor y02 x02)))
(ignore-errors (defparameter z41 (xor jhf pgs)))
(ignore-errors (defparameter z00 (xor x00 y00)))
(ignore-errors (defparameter z18 (xor stq dgj)))
(ignore-errors (defparameter vns (and cqb pbd)))
(ignore-errors (defparameter dck (xor x06 y06)))
(ignore-errors (defparameter ggh (or qwg bdr)))
(ignore-errors (defparameter tnm (and x36 y36)))
(ignore-errors (defparameter pjb (xor x09 y09)))
(ignore-errors (defparameter tdm (or hdw tnm)))
(ignore-errors (defparameter rwc (and vjq cpr)))
(ignore-errors (defparameter bnv (xor y21 x21)))
(ignore-errors (defparameter qkd (or rwc pqp)))
(ignore-errors (defparameter nhp (and qgg pbq)))
(ignore-errors (defparameter ggw (and y07 x07)))
(ignore-errors (defparameter z14 (xor hgw wss)))
(ignore-errors (defparameter cnn (xor y25 x25)))
(ignore-errors (defparameter z37 (xor tdm pvc)))
(ignore-errors (defparameter qwg (and jdt rsm)))
(ignore-errors (defparameter bkg (and y05 x05)))
(ignore-errors (defparameter rsm (or dhh jdj)))
(ignore-errors (defparameter dnn (and djg kpw)))
(ignore-errors (defparameter z20 (xor qgg pbq)))
(ignore-errors (defparameter ntv (and gtc mjj)))
(ignore-errors (defparameter frj (or tgg frc)))
(ignore-errors (defparameter jth (and y16 x16)))
(ignore-errors (defparameter fhs (xor y23 x23)))
(ignore-errors (defparameter jsb (and x24 y24)))
(ignore-errors (defparameter bst (or pgq dgr)))
(ignore-errors (defparameter wss (and x14 y14)))
(ignore-errors (defparameter jhf (or rbt sng)))
(ignore-errors (defparameter qbb (and y10 x10)))
(ignore-errors (defparameter z03 (xor rsm jdt)))
(ignore-errors (defparameter pfk (xor y31 x31)))
(ignore-errors (defparameter vsr (and vkv bbc)))
(ignore-errors (defparameter vsn (xor y01 x01)))
(ignore-errors (defparameter mbr (or tpp hct)))
(ignore-errors (defparameter bgq (and qvq cdn)))
(ignore-errors (defparameter cdn (xor y32 x32)))
(ignore-errors (defparameter qwd (and x21 y21)))
(ignore-errors (defparameter hfw (xor y04 x04)))
(ignore-errors (defparameter ppk (xor y17 x17)))
(ignore-errors (defparameter rpq (and bfq dcf)))
(ignore-errors (defparameter spd (and ggh hfw)))
(ignore-errors (defparameter jdt (xor x03 y03)))
(ignore-errors (defparameter ktg (and jbd pvb)))
(ignore-errors (defparameter stq (xor x18 y18)))
(ignore-errors (defparameter gng (and x34 y34)))
(ignore-errors (defparameter sng (and y40 x40)))
(ignore-errors (defparameter ksh (and x33 y33)))
(ignore-errors (defparameter z06 (xor qrb dck)))
(ignore-errors (defparameter pmf (xor x26 y26)))
(ignore-errors (defparameter z01 (xor vsn rhk)))
(ignore-errors (defparameter pgq (and frj rbr)))
(ignore-errors (defparameter mpr (and x08 y08)))
(ignore-errors (defparameter knw (and cdf cmn)))
(ignore-errors (defparameter qvq (or wjp qdj)))
(ignore-errors (defparameter fdc (and fjs fhs)))
(ignore-errors (defparameter jmb (xor x07 y07)))
(ignore-errors (defparameter hdw (and qvh fpc)))
(ignore-errors (defparameter bbc (xor x34 y34)))
(ignore-errors (defparameter dhr (or ghm ghc)))
(ignore-errors (defparameter sft (and rmm vmv)))
(ignore-errors (defparameter z43 (xor ktr qkd)))
(ignore-errors (defparameter hqs (or knk sjw)))
(ignore-errors (defparameter qbn (xor y40 x40)))
(ignore-errors (defparameter dnk (or bgs mfj)))
(ignore-errors (defparameter z39 (xor pmq ggj)))
(ignore-errors (defparameter gst (or qrq qbb)))
(ignore-errors (defparameter mpj (xor y35 x35)))
(ignore-errors (defparameter z44 (xor rrq gjw)))
(ignore-errors (defparameter z34 (xor vkv bbc)))
(ignore-errors (defparameter ktr (xor y43 x43)))
(ignore-errors (defparameter djg (or qcj ntv)))
(ignore-errors (defparameter z19 (xor wfs grf)))
(ignore-errors (defparameter ftn (xor x10 y10)))
(ignore-errors (defparameter pvb (or chb spd)))
(ignore-errors (defparameter rbr (xor x27 y27)))
(ignore-errors (defparameter dhh (and y02 x02)))
(ignore-errors (defparameter z32 (xor qvq cdn)))
(ignore-errors (defparameter z28 (xor bst stp)))
(ignore-errors (defparameter wrm (xor x14 y14)))
(ignore-errors (defparameter vgw (and y17 x17)))
(ignore-errors (defparameter qvh (xor x36 y36)))
(ignore-errors (defparameter jrk (and x20 y20)))
(ignore-errors (defparameter ptf (and x35 y35)))
(ignore-errors (defparameter ntb (and bnv nhj)))
(ignore-errors (defparameter rws (and cnn dwm)))
(ignore-errors (defparameter hwq (xor cmn cdf)))
(ignore-errors (defparameter tbc (and pjb dnc)))
(ignore-errors (defparameter ghm (and x39 y39)))
(ignore-errors (defparameter vqp (xor x08 y08)))
(ignore-errors (defparameter hgw (or cmd vns)))
(ignore-errors (defparameter z29 (or grd rpq)))
(ignore-errors (defparameter grd (and y29 x29)))
(ignore-errors (defparameter pvc (xor y37 x37)))
(ignore-errors (defparameter wjp (and hvf pfk)))

(defparameter *answer* (format nil "~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~a~%" (if z00 1 0) (if z01 1 0) (if z02 1 0) (if z03 1 0) (if z04 1 0) (if z05 1 0) (if z06 1 0) (if z07 1 0) (if z08 1 0) (if z09 1 0) (if z10 1 0) (if z11 1 0) (if z12 1 0) (if z13 1 0) (if z14 1 0) (if z15 1 0) (if z16 1 0) (if z17 1 0) (if z18 1 0) (if z19 1 0) (if z20 1 0) (if z21 1 0) (if z22 1 0) (if z23 1 0) (if z24 1 0) (if z25 1 0) (if z26 1 0) (if z27 1 0) (if z28 1 0) (if z29 1 0) (if z30 1 0) (if z31 1 0) (if z32 1 0) (if z33 1 0) (if z34 1 0) (if z35 1 0) (if z36 1 0) (if z37 1 0) (if z38 1 0) (if z39 1 0) (if z40 1 0) (if z41 1 0) (if z42 1 0) (if z43 1 0) (if z44 1 0) (if z45 1 0)))

(format t (reverse *answer*))